export const callendar_theme = {
    backgroundColor: '#A80742',
    calendarBackground: '#810e13',
    textSectionTitleColor: '#FFFFFF',
    selectedDayBackgroundColor: '#FF6347',
    selectedDayTextColor: '#FFFFFF',
    todayTextColor: '#FFA500',
    dayTextColor: '#FFFFFF',
    textDisabledColor: '#666666',
    dotColor: '#FF6347',
    selectedDotColor: '#FFFFFF',
    arrowColor: '#FFA500',
    monthTextColor: '#FFFFFF',
    indicatorColor: '#FFA500',
};